---
title: "Overview"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Background

Adverse drug reactions are a leading cause of morbidity and mortality that costs billions of dollars for the healthcare system. In children, there is increased risk for adverse drug reactions with potentially lasting adverse effects into adulthood. The current pediatric drug safety landscape, including clinical trials, is limited as it rarely includes children and relies on extrapolation from adults. Children are not small adults but go through an evolutionarily conserved and physiologically dynamic process of growth and maturation. We hypothesize that adverse drug reactions manifest from the interaction between drug exposure and dynamic biological processes during child growth and development.

We hypothesize that by developing statistical methodologies with prior knowledge of dynamic, shared information during development, we can improve the detection of adverse drug events in children. This data package downloads the SQLite database created by applying covariate-adjusted disproportionality generalized additive models (dGAMs) in a systematic way to develop a resource of nearly half a million adverse drug event (ADE) risk estimates across child development stages.

# Pediatric Drug Safety (PDS) data

## Observation-level data

The observation-level data, case reports for drug(s) potentially linked to adverse event(s), was collected by the Food and Drug Administration Adverse Event System (FAERS) in the US. This data is publicly available on the openFDA platform [here](https://open.fda.gov/data/downloads/) as downloadable [json files](https://api.fda.gov/download.json). However, utilizing this data as-is is non-trivial, where the drug event report data is published in chunks as a nested json structure each quarter per year since the 1990s. With an API key with extended permissions, I developed custom python notebooks and scripts available in the ‘openFDA_drug_event-parsing’ github repository (DOI: https://doi.org/10.5281/zenodo.4464544) to extract and format all drug event reports prior to the third quarter of 2019. This observation-level data used, called Pediatric FAERS, for downstream analyses is stored in the table `ade_raw`.

## Summary-level data

The drugs and adverse events reported were coded into standard, hierarchical vocabularies. Adverse events were standardized by the Medical Dictionary of Regulatory Activities (MedDRA) vocabulary (details of the hierarchy founds [here](https://www.meddra.org/how-to-use/basics/hierarchy)). Drugs were standardized by the Anatomical Therapeutic Class (ATC) vocabulary (details found [here](https://www.who.int/tools/atc-ddd-toolkit/atc-classification)). The reporting of adverse events and drugs can be dependent on the disease context of a report's subject. This was represented by summarizing the number of drugs of a therapeutic class for each report. 

## Model-level data

We invented the disproportionality generalized additive model (dGAM) method for detecting adverse drug events from these spontaneous reports. We applied the logistic generalized additive model to all unique drug-event pairs in Pediatric FAERS. The drug-event GAM was used to quantify adverse event risk due to drug exposure versus no exposure across child development stages. Please see the references for the full specification and details on the GAM.

# PDSportal: accessible data access

We provide the [PDSportal](https://pdsportal.shinyapps.io/pdsportal/) as an accessible web application as well as a plaatform to download our database for the community to explore from identifying safety endpoints in clinical trials to evaluating known and novel developmental pharmacology. 

# KidSIDES

The `kidsides` R package downloads a sqlite database to your local machine and connects to the database using the `DBI` R package. This is a novel data resource of half a million pediatric drug safety signals across growth and development stages. Please see the references for details on data fields and the [code repository](https://github.com/ngiangre/pediatric_ade_database_study) for the [paper](https://doi.org/10.1016/j.medj.2022.06.001).

# References


Giangreco, Nicholas. Mind the developmental gap: Identifying adverse drug effects across childhood to evaluate biological mechanisms from growth and development. 2022. Columbia University, [PhD dissertation](https://doi.org/10.7916/d8-5d9b-6738).

Giangreco NP, Tatonetti NP. A database of pediatric drug effects to evaluate ontogenic mechanisms from child growth and development. Med (N Y). 2022 Aug 12;3(8):579-595.e7. [doi: 10.1016/j.medj.2022.06.001](https://doi.org/10.1016/j.medj.2022.06.001). Epub 2022 Jun 24. PMID: 35752163; PMCID: PMC9378670.


